
package com.mycompany.proyecto1_poo_2023;

import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;


public class CreateDefenses extends javax.swing.JFrame {

    /**
     * Creates new form CreateDefenses
     */
    public CreateDefenses() {
    JLValidation = new javax.swing.JLabel();
    getContentPane().add(JLValidation);
    JLValidation.setBounds(365, 550, 400, 16);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlInfo = new javax.swing.JLabel();
        JlAppearanceLevel = new javax.swing.JLabel();
        JlSpace = new javax.swing.JLabel();
        JlTitle = new javax.swing.JLabel();
        JlDefenseType = new javax.swing.JLabel();
        JlName = new javax.swing.JLabel();
        JlAppearance = new javax.swing.JLabel();
        JlActionRange = new javax.swing.JLabel();
        JlLife = new javax.swing.JLabel();
        JlInfoRequest = new javax.swing.JLabel();
        JTFLevelAppearance = new javax.swing.JTextField();
        JlDPS = new javax.swing.JLabel();
        JTFName = new javax.swing.JTextField();
        JTFLife = new javax.swing.JTextField();
        JTFDamage = new javax.swing.JTextField();
        JFTSpace = new javax.swing.JTextField();
        JTFdps = new javax.swing.JTextField();
        CBoxDefenseType = new javax.swing.JComboBox<>();
        ImageChooser = new javax.swing.JButton();
        JButCrearDefensa = new javax.swing.JButton();
        JlBackgroundZom = new javax.swing.JLabel();

        JlInfo.setText("En esta ventana podra crear un elemento del juego de tipo defensa");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 585));
        getContentPane().setLayout(null);

        JlAppearanceLevel.setText("Nivel de aparicion:");
        getContentPane().add(JlAppearanceLevel);
        JlAppearanceLevel.setBounds(590, 410, 120, 16);

        JlSpace.setText("Campos");
        getContentPane().add(JlSpace);
        JlSpace.setBounds(590, 270, 100, 16);

        JlTitle.setText("Crear Defensas");
        getContentPane().add(JlTitle);
        JlTitle.setBounds(356, 45, 110, 30);

        JlDefenseType.setText("Tipo de Defensa:");
        getContentPane().add(JlDefenseType);
        JlDefenseType.setBounds(130, 350, 120, 16);

        JlName.setText("Nombre:");
        getContentPane().add(JlName);
        JlName.setBounds(130, 170, 70, 20);

        JlAppearance.setText("Apariencia");
        getContentPane().add(JlAppearance);
        JlAppearance.setBounds(130, 260, 120, 16);

        JlActionRange.setText("Cantidad de golpes");
        getContentPane().add(JlActionRange);
        JlActionRange.setBounds(590, 340, 170, 16);

        JlLife.setText("Unidad de vida");
        getContentPane().add(JlLife);
        JlLife.setBounds(130, 410, 120, 16);

        JlInfoRequest.setText("Ingrese los datos solicitados para crear una defensa");
        getContentPane().add(JlInfoRequest);
        JlInfoRequest.setBounds(300, 130, 290, 16);

        JTFLevelAppearance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFLevelAppearanceActionPerformed(evt);
            }
        });
        getContentPane().add(JTFLevelAppearance);
        JTFLevelAppearance.setBounds(590, 440, 110, 30);

        JlDPS.setText("Damage ");
        getContentPane().add(JlDPS);
        JlDPS.setBounds(590, 190, 180, 16);

        JTFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNameActionPerformed(evt);
            }
        });
        getContentPane().add(JTFName);
        JTFName.setBounds(130, 200, 110, 30);

        JTFLife.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFLifeActionPerformed(evt);
            }
        });
        getContentPane().add(JTFLife);
        JTFLife.setBounds(130, 430, 110, 30);

        JTFDamage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFDamageActionPerformed(evt);
            }
        });
        getContentPane().add(JTFDamage);
        JTFDamage.setBounds(590, 220, 110, 30);

        JFTSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFTSpaceActionPerformed(evt);
            }
        });
        getContentPane().add(JFTSpace);
        JFTSpace.setBounds(590, 300, 110, 30);

        JTFdps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFdpsActionPerformed(evt);
            }
        });
        getContentPane().add(JTFdps);
        JTFdps.setBounds(590, 370, 110, 30);

        CBoxDefenseType.setBackground(new java.awt.Color(0, 102, 102));
        CBoxDefenseType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "melee", "airtype", "mediumrange", "kamikaze", "wall", "nexus" }));
        CBoxDefenseType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxDefenseTypeActionPerformed(evt);
            }
        });
        getContentPane().add(CBoxDefenseType);
        CBoxDefenseType.setBounds(130, 370, 140, 26);

        ImageChooser.setBackground(new java.awt.Color(0, 153, 153));
        ImageChooser.setText("Choose a file!");
        ImageChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageChooserActionPerformed(evt);
            }
        });
        getContentPane().add(ImageChooser);
        ImageChooser.setBounds(130, 290, 190, 24);

        JButCrearDefensa.setBackground(new java.awt.Color(102, 153, 0));
        JButCrearDefensa.setText("Terminar Defensa");
        JButCrearDefensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButCrearDefensaActionPerformed(evt);
            }
        });
        getContentPane().add(JButCrearDefensa);
        JButCrearDefensa.setBounds(360, 510, 140, 24);

        JlBackgroundZom.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alonso D\\OneDrive\\Documents\\NetBeansProjects\\ConfComponentesPOO1\\ConfComponentesPOO1\\src\\main\\java\\Images\\PantallaDefensa.jpg")); // NOI18N
        JlBackgroundZom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        getContentPane().add(JlBackgroundZom);
        JlBackgroundZom.setBounds(0, 0, 860, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFLevelAppearanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFLevelAppearanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFLevelAppearanceActionPerformed

    private void JTFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNameActionPerformed

    private void JTFLifeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFLifeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFLifeActionPerformed

    private void JTFDamageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFDamageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFDamageActionPerformed

    private void JFTSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFTSpaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFTSpaceActionPerformed

    private void JTFdpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFdpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFdpsActionPerformed

    private void CBoxDefenseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxDefenseTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxDefenseTypeActionPerformed
    private String selectedImagePath;
    
    private void ImageChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageChooserActionPerformed
       SwingUtilities.invokeLater(() -> {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Choose a file");
            fileChooser.setPreferredSize(new Dimension(700, 700));

            int result = fileChooser.showOpenDialog(this);

            if (result == JFileChooser.APPROVE_OPTION) {
                File selectedFile = fileChooser.getSelectedFile();

                if (isValidImageFile(selectedFile)) {
                    System.out.println("Valid image file selected: " + selectedFile);
                    selectedImagePath = selectedFile.getAbsolutePath(); // Save the selected image path
                } else {
                    System.out.println("Invalid image file selected");
                    showValidationMessage("Please choose a valid image file (e.g., PNG, JPG).");
                }
            } else {
                System.out.println("No file selected");
            }
        });
    }//GEN-LAST:event_ImageChooserActionPerformed
    
    private void JButCrearDefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButCrearDefensaActionPerformed
    // Validate fields before proceeding
    if (!validateFields() || selectedImagePath == null) {
        if (selectedImagePath == null) {
                showValidationMessage("Please choose an image file.");
            }
        return;  // Stop execution if fields are not valid
    }

    String name = JTFName.getText();
    int levelAppearance = Integer.parseInt(JTFLevelAppearance.getText());
    int life = Integer.parseInt(JTFLife.getText());
    int damage = Integer.parseInt(JTFDamage.getText());
    int spaces = Integer.parseInt(JFTSpace.getText());
    int dps = Integer.parseInt(JTFdps.getText());

    // Get the selected ZombieType directly from the JComboBox
    String defenseTypeString = CBoxDefenseType.getSelectedItem().toString();

    // Map the String to the ZombieType enum
    Defenses.DefenseType defenseTypeEnum = Defenses.DefenseType.valueOf(defenseTypeString.toUpperCase());

    // Create a Zombie object
    Defenses defense = new Defenses(defenseTypeEnum, name, 0,0 , 
                                levelAppearance, damage, spaces, dps, "", selectedImagePath);
   
    JFileChooser fileChooser = new JFileChooser();
    // Configura el filtro de extensiones (opcional)
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos.ser", "ser");
    fileChooser.setFileFilter(filter);
    int userChoice = fileChooser.showSaveDialog(this); // 'this' refers to the current JFrame
    
    if (userChoice == JFileChooser.APPROVE_OPTION) {
        // El usuario ha elegido guardar el archivo en la ubicación seleccionada
        String filePath = fileChooser.getSelectedFile().getAbsolutePath() + ".ser";
        FileManager.writeObject(defense, filePath);
        System.out.println("Zombie guardado exitosamente en: " + filePath);
    } else if (userChoice == JFileChooser.CANCEL_OPTION) {
        // El usuario ha cancelado la operación
        System.out.println("Operación de guardar cancelada.");
    }
    
    // For demonstration purposes, let's just print the details
    System.out.println("Defense created successfully!");
    System.out.println("Name: " + name);
    System.out.println("Level of Appearance: " + levelAppearance);
    System.out.println("Life: " + life);
    System.out.println("Damage " + damage);
    System.out.println("Spaces: " + spaces);
    System.out.println("Nhits: " + dps);
    System.out.println("Defense Type: " + defense.getType());
    System.out.println("Image Path:" + selectedImagePath);
    
    System.out.println("Prueba");

    // Clear validation message after successful validation
    clearValidationMessage();
    
    this.dispose(); // Assuming this is your JFrame

    // Open or show the selection window
    SelectionWindow selectionWindow = new SelectionWindow();
    selectionWindow.setVisible(true);
    }//GEN-LAST:event_JButCrearDefensaActionPerformed
 
    private boolean validateFields() {
    if (JTFName.getText().isEmpty()) {
        showValidationMessage("Please enter a name.");
        return false;
    }
    String name = JTFName.getText();
    if (name.length() < 2 || name.length() > 15) {
        showValidationMessage("Please enter a name between 2 and 15 characters.");
        return false;
    }
    
    if (JTFLevelAppearance.getText().isEmpty()) {
        showValidationMessage("Please enter a level of appearance.");
        return false;
    }

    // Validate that the level of appearance is a positive integer
    try {
        int levelAppearance = Integer.parseInt(JTFLevelAppearance.getText());
        if (levelAppearance <= 0) {
            showValidationMessage("Please enter a valid positive level of appearance.");
            return false;
        }
    } catch (NumberFormatException e) {
        showValidationMessage("Please enter a valid numeric value for the level of appearance.");
        return false;
    }

    if (JTFLife.getText().isEmpty()) {
        showValidationMessage("Please enter a life unit.");
        return false;
    }

    // Validate that life is a non-negative integer
    if (!isNonNegativeInteger(JTFLife.getText())) {
        showValidationMessage("Please enter a valid non-negative integer for life.");
        return false;
    }

    if (JTFDamage.getText().isEmpty()) {
        showValidationMessage("Please enter DPS (Damage Per Second).");
        return false;
    }

    // Validate that DPS is a non-negative integer
    if (!isNonNegativeInteger(JTFDamage.getText())) {
        showValidationMessage("Please enter a valid non-negative integer for DPS.");
        return false;
    }

    if (JFTSpace.getText().isEmpty()) {
        showValidationMessage("Please enter the number of spaces.");
        return false;
    }

    // Validate that spaces is a non-negative integer
    if (!isNonNegativeInteger(JFTSpace.getText())) {
        showValidationMessage("Please enter a valid non-negative integer for spaces.");
        return false;
    }

    if (JTFdps.getText().isEmpty()) {
        showValidationMessage("Please enter the action range.");
        return false;
    }

    // Validate that action range is a non-negative integer
    if (!isNonNegativeInteger(JTFdps.getText())) {
        showValidationMessage("Please enter a valid non-negative integer for action range.");
        return false;
    }

    // Add similar checks for other fields...

    return true;
}

// Utility method to check if a string is a non-negative integer
private boolean isNonNegativeInteger(String str) {
    try {
        int value = Integer.parseInt(str);
        return value >= 0;
    } catch (NumberFormatException e) {
        return false;
    }
}

private void showValidationMessage(String message) {
    JLValidation.setText(message);
    JLValidation.setForeground(Color.RED);
}

private void clearValidationMessage() {
    JLValidation.setText("");
}
private boolean isValidImageFile(File file) {
    //Check if the file has a valid image format 
    return file != null && file.isFile() && isImageFile(file.getName());
}

// Utility method to check if a file has an image extension
private boolean isImageFile(String fileName) {
    String[] allowedExtensions = {".png", ".jpg", ".jpeg", ".gif", ".bmp"}; 
    String lowerCaseFileName = fileName.toLowerCase();

    for (String extension : allowedExtensions) {
        if (lowerCaseFileName.endsWith(extension)) {
            return true;
        }
    }

    return false;
}

    private static void readSerializedDefense(String filePath1) {
        // Read the serialized Defense object from the file
        Object obj = FileManager.readObject(filePath1);

        if (obj instanceof Defenses) {
            // Cast the object to Defense type
            Defenses defense = (Defenses) obj;

            // Now you can access the properties of the Defense object
            System.out.println("Defense Name: " + defense.getId());
            System.out.println("Level of Appearance: " + defense.getUnlockLevel());
            // Add more properties as needed...

        } else {
            System.out.println("The file does not contain a valid Defense object: " + filePath1);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateDefenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateDefenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateDefenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateDefenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateDefenses().setVisible(true);
            }
        });
    }
    
    private javax.swing.JLabel JLValidation;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBoxDefenseType;
    private javax.swing.JButton ImageChooser;
    private javax.swing.JButton JButCrearDefensa;
    private javax.swing.JTextField JFTSpace;
    private javax.swing.JTextField JTFDamage;
    private javax.swing.JTextField JTFLevelAppearance;
    private javax.swing.JTextField JTFLife;
    private javax.swing.JTextField JTFName;
    private javax.swing.JTextField JTFdps;
    private javax.swing.JLabel JlActionRange;
    private javax.swing.JLabel JlAppearance;
    private javax.swing.JLabel JlAppearanceLevel;
    private javax.swing.JLabel JlBackgroundZom;
    private javax.swing.JLabel JlDPS;
    private javax.swing.JLabel JlDefenseType;
    private javax.swing.JLabel JlInfo;
    private javax.swing.JLabel JlInfoRequest;
    private javax.swing.JLabel JlLife;
    private javax.swing.JLabel JlName;
    private javax.swing.JLabel JlSpace;
    private javax.swing.JLabel JlTitle;
    // End of variables declaration//GEN-END:variables
}
