
package com.mycompany.proyecto1_poo_2023;

import java.awt.Window;
import javax.swing.JFrame;



public class ContinueGameLoss extends javax.swing.JFrame {
    
    MainWindow gameWindow;       
    GameManager manager;
            
    public ContinueGameLoss(MainWindow gameWindow, GameManager manager) {
        this.manager=manager;
        this.gameWindow=gameWindow;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        JbExit = new javax.swing.JButton();
        JbPassGame = new javax.swing.JButton();
        JbRepeatGame = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(866, 416));
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 153, 51));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   Como desea proseguir?");
        jLabel2.setToolTipText("");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 20, 320, 50);

        JbExit.setText("Salir del juego");
        JbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbExitActionPerformed(evt);
            }
        });
        getContentPane().add(JbExit);
        JbExit.setBounds(350, 330, 180, 60);

        JbPassGame.setText("Continuar a siguiente nivel");
        JbPassGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbPassGameActionPerformed(evt);
            }
        });
        getContentPane().add(JbPassGame);
        JbPassGame.setBounds(160, 250, 250, 60);

        JbRepeatGame.setText("Repetir nivel");
        JbRepeatGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbRepeatGameActionPerformed(evt);
            }
        });
        getContentPane().add(JbRepeatGame);
        JbRepeatGame.setBounds(530, 250, 180, 60);

        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 90, 41, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alonso D\\OneDrive\\Documents\\NetBeansProjects\\Proyecto1POO2023\\Proyecto1_POO_2023\\Images\\LostGame_1.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 870, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbPassGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbPassGameActionPerformed
      
        int level = manager.getCurrentLevel()+1;
        MainWindow newWindow = new MainWindow(level);
        newWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JbPassGameActionPerformed

    private void JbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbExitActionPerformed
        Window[] windows = Window.getWindows();
        for (Window window : windows) {
            if (window instanceof JFrame) {
                ((JFrame) window).dispose();
            }
        }
    }//GEN-LAST:event_JbExitActionPerformed

    private void JbRepeatGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbRepeatGameActionPerformed
        int level = manager.getCurrentLevel();
        MainWindow newWindow = new MainWindow(level);
        gameWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JbRepeatGameActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbExit;
    private javax.swing.JButton JbPassGame;
    private javax.swing.JButton JbRepeatGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
